import {
  extractYouTubeTranscriptDetailed,
  linesFromEvents,
  normalizeYouTubeUrl,
  TranscriptExtractionError,
  videoId,
} from "./transcript/youtubeTranscriptService.js";

export { linesFromEvents, normalizeYouTubeUrl, videoId };

function timecode(seconds) {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const rest = seconds - hours * 3600 - minutes * 60;
  return hours
    ? `${hours}:${String(minutes).padStart(2, "0")}:${rest.toFixed(3).padStart(6, "0")}`
    : `${minutes}:${rest.toFixed(3).padStart(6, "0")}`;
}

function successPayload(result, rawInput, normalizedUrl) {
  const extractor = result.extractor;
  const lines = result.subtitles.map((item) => ({
    text_en: item.text,
    time_start: timecode(item.start),
    time_end: timecode(item.start + item.duration),
  }));
  return {
    videoId: result.videoId,
    title: result.title,
    language: result.language,
    isAutoGenerated: result.isAutoGenerated,
    subtitles: result.subtitles,
    lines,
    diagnostics: {
      rawInput,
      normalizedUrl,
      videoId: result.videoId,
      apiUrl: "/api/youtube-transcript",
      extractor,
      captionTracksFound: result.diagnostics.find(
        (item) => item.extractor === extractor && item.step === "caption-tracks",
      )?.found || 0,
      subtitleCount: result.subtitles.length,
      attempt: result.attempt,
      upstream: result.diagnostics,
    },
  };
}

async function fetchIndependentService(serviceUrl, body, env) {
  const endpoint = `${String(serviceUrl).replace(/\/+$/, "")}/transcript`;
  const headers = { "Content-Type": "application/json", Accept: "application/json" };
  if (env.TRANSCRIPT_SERVICE_TOKEN) headers.Authorization = `Bearer ${env.TRANSCRIPT_SERVICE_TOKEN}`;
  let response;
  try {
    response = await fetch(endpoint, {
      method: "POST",
      headers,
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(45_000),
    });
  } catch (cause) {
    const error = new Error("Transcript tunnel network request failed");
    error.reason = "transcript_tunnel_network_error";
    error.cause = cause;
    throw error;
  }
  const raw = await response.text();
  let result = null;
  try { result = JSON.parse(raw); } catch { /* Surface only a short response excerpt below. */ }
  if (!response.ok) {
    const detail = result?.error || raw.replace(/\s+/g, " ").slice(0, 180);
    const error = new Error(`独立字幕服务返回 HTTP ${response.status}${detail ? `: ${detail}` : ""}`);
    error.statusCode = response.status;
    error.upstreamReason = result?.reason || null;
    error.attemptCount = result?.attemptCount || 0;
    error.attempts = result?.attempts || [];
    error.reason = result?.reason === "youtube_bot_challenge" || result?.reason === "youtube_transcript_unavailable"
      ? result.reason
      : "transcript_tunnel_http_error";
    throw error;
  }
  if (!result?.videoId || !Array.isArray(result.subtitles) || result.subtitles.length === 0) {
    const error = new Error("独立字幕服务没有返回有效字幕");
    error.statusCode = response.status;
    error.reason = "transcript_service_invalid_response";
    throw error;
  }
  return result;
}

export async function handleYouTubeTranscript(_req, res, body, env = process.env) {
  const rawInput = String(body?.url || "");
  const normalizedUrl = normalizeYouTubeUrl(rawInput);
  if (env.TRANSCRIPT_SERVICE_URL || env.VERCEL) {
    if (!env.TRANSCRIPT_SERVICE_URL) {
      res.statusCode = 503;
      res.end(JSON.stringify({
        error: "Independent transcript service is not configured",
        reason: "transcript_service_not_configured",
        diagnostics: { rawInput, normalizedUrl, videoId: videoId(rawInput), subtitleCount: 0 },
      }));
      return;
    }
    try {
      const result = await fetchIndependentService(env.TRANSCRIPT_SERVICE_URL, { url: rawInput }, env);
      const lines = result.subtitles.map((item) => ({
        text_en: item.text,
        time_start: timecode(item.start),
        time_end: timecode(item.start + item.duration),
      }));
      res.statusCode = 200;
      res.end(JSON.stringify({
        videoId: result.videoId,
        title: result.title || "",
        language: result.language || "en",
        isAutoGenerated: result.isAutoGenerated ?? false,
        subtitles: result.subtitles,
        lines,
        diagnostics: {
          rawInput,
          normalizedUrl,
          videoId: result.videoId,
          apiUrl: "/api/youtube-transcript",
          extractor: "independent-transcript-service",
          subtitleCount: result.subtitles.length,
        },
      }));
      return;
    } catch (error) {
      const cause = error?.cause;
      const serviceError = [
        error?.message || "independent_service_unavailable",
        cause?.code,
        cause?.message,
      ].filter(Boolean).join(": ").slice(0, 300);
      res.statusCode = 502;
      res.end(JSON.stringify({
        error: serviceError,
        reason: error?.reason || "transcript_service_error",
        diagnostics: {
          rawInput,
          normalizedUrl,
          videoId: videoId(rawInput),
          apiUrl: "/api/youtube-transcript",
          subtitleCount: 0,
          transcriptService: {
            status: error?.statusCode || null,
            reason: error?.upstreamReason || error?.reason || null,
            attemptCount: error?.attemptCount || 0,
            attempts: error?.attempts || [],
          },
        },
      }));
      return;
    }
  }
  try {
    const result = await extractYouTubeTranscriptDetailed(rawInput);
    res.statusCode = 200;
    res.end(JSON.stringify(successPayload(result, rawInput, normalizedUrl)));
  } catch (error) {
    const knownError = error instanceof TranscriptExtractionError;
    const statusCode = knownError ? error.statusCode : 502;
    const diagnostics = knownError ? error.diagnostics : [];
    const isBotChallenge = knownError && error.reason === "youtube_bot_challenge";
    res.statusCode = statusCode;
    res.end(JSON.stringify({
      error: isBotChallenge
        ? "Vercel 服务器被 YouTube bot challenge 拦截，无法读取该视频已有的 CC Transcript；请在真实 YouTube 页面使用『导入 LingoClub』"
        : error?.message || "未能读取 YouTube 已有英文 CC Transcript",
      reason: knownError ? error.reason : "transcript_unavailable",
      errors: knownError ? error.errors : [],
      diagnostics: {
        rawInput,
        normalizedUrl,
        videoId: videoId(rawInput),
        apiUrl: "/api/youtube-transcript",
        captionTracksFound: Math.max(0, ...diagnostics
          .filter((item) => item.step === "caption-tracks")
          .map((item) => item.found || 0)),
        subtitleCount: 0,
        upstream: diagnostics,
      },
    }));
  }
}
