import {
  extractYouTubeTranscriptDetailed,
  linesFromEvents,
  normalizeYouTubeUrl,
  TranscriptExtractionError,
  videoId,
} from "./transcript/youtubeTranscriptService.js";

export { linesFromEvents, normalizeYouTubeUrl, videoId };

const TRANSCRIPT_CACHE_TTL_MS = 30 * 24 * 60 * 60 * 1000;
const transcriptCache = new Map();
const transcriptRequests = new Map();

function timecode(seconds) {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const rest = seconds - hours * 3600 - minutes * 60;
  return hours
    ? `${hours}:${String(minutes).padStart(2, "0")}:${rest.toFixed(3).padStart(6, "0")}`
    : `${minutes}:${rest.toFixed(3).padStart(6, "0")}`;
}

function successPayload(result, rawInput, normalizedUrl, { cached = false, serviceFallback = null } = {}) {
  const extractor = result.extractor;
  const lines = result.subtitles.map((item) => ({
    text_en: item.text,
    time_start: timecode(item.start),
    time_end: timecode(item.start + item.duration),
  }));
  return {
    videoId: result.videoId,
    title: result.title,
    language: result.language,
    isAutoGenerated: result.isAutoGenerated,
    subtitles: result.subtitles,
    lines,
    diagnostics: {
      rawInput,
      normalizedUrl,
      videoId: result.videoId,
      apiUrl: "/api/youtube-transcript",
      extractor,
      cached,
      transcriptService: serviceFallback,
      captionTracksFound: result.diagnostics.find(
        (item) => item.extractor === extractor && item.step === "caption-tracks",
      )?.found || 0,
      subtitleCount: result.subtitles.length,
      attempt: result.attempt,
      upstream: result.diagnostics,
    },
  };
}

async function fetchIndependentService(serviceUrl, body, env) {
  const endpoint = `${String(serviceUrl).replace(/\/+$/, "")}/transcript`;
  const headers = { "Content-Type": "application/json", Accept: "application/json" };
  if (env.TRANSCRIPT_SERVICE_TOKEN) headers.Authorization = `Bearer ${env.TRANSCRIPT_SERVICE_TOKEN}`;
  let response;
  try {
    response = await fetch(endpoint, {
      method: "POST",
      headers,
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(6_000),
    });
  } catch (cause) {
    const error = new Error("Transcript tunnel network request failed");
    error.reason = "transcript_tunnel_network_error";
    error.cause = cause;
    throw error;
  }
  const raw = await response.text();
  let result = null;
  try { result = JSON.parse(raw); } catch { /* Surface only a short response excerpt below. */ }
  if (!response.ok) {
    const detail = result?.error || raw.replace(/\s+/g, " ").slice(0, 180);
    const error = new Error(`独立字幕服务返回 HTTP ${response.status}${detail ? `: ${detail}` : ""}`);
    error.statusCode = response.status;
    error.upstreamReason = result?.reason || null;
    error.attemptCount = result?.attemptCount || 0;
    error.attempts = result?.attempts || [];
    error.reason = result?.reason === "youtube_bot_challenge" || result?.reason === "youtube_transcript_unavailable"
      ? result.reason
      : "transcript_tunnel_http_error";
    throw error;
  }
  if (!result?.videoId || !Array.isArray(result.subtitles) || result.subtitles.length === 0) {
    const error = new Error("独立字幕服务没有返回有效字幕");
    error.statusCode = response.status;
    error.reason = "transcript_service_invalid_response";
    throw error;
  }
  return result;
}

const wait = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));

function cacheTranscript(id, value) {
  if (transcriptCache.size >= 200) transcriptCache.delete(transcriptCache.keys().next().value);
  transcriptCache.set(id, { savedAt: Date.now(), value });
}

async function resolveTranscript(rawInput, env) {
  let serviceFallback = null;
  if (env.TRANSCRIPT_SERVICE_URL) {
    try {
      const serviceResult = await fetchIndependentService(env.TRANSCRIPT_SERVICE_URL, { url: rawInput }, env);
      return {
        result: {
          videoId: serviceResult.videoId,
          title: serviceResult.title || "",
          language: serviceResult.language || "en",
          isAutoGenerated: serviceResult.isAutoGenerated ?? false,
          subtitles: serviceResult.subtitles,
          extractor: "independent-transcript-service",
          diagnostics: [],
          attempt: serviceResult.attemptCount || 1,
        },
        serviceFallback: { configured: true, used: true, status: 200, reason: null },
      };
    } catch (error) {
      serviceFallback = {
        configured: true,
        used: false,
        status: error?.statusCode || null,
        reason: error?.upstreamReason || error?.reason || "transcript_service_error",
      };
    }
  }

  let lastError;
  try {
    const result = await extractYouTubeTranscriptDetailed(rawInput, { attempts: 3, retryDelayMs: 250 });
    if (serviceFallback) serviceFallback.used = true;
    else serviceFallback = { configured: false, used: true, reason: "direct_extractor" };
    return { result, serviceFallback };
  } catch (error) {
    lastError = error;
  }
  if (serviceFallback) lastError.serviceFallback = serviceFallback;
  throw lastError;
}

export async function handleYouTubeTranscript(_req, res, body, env = process.env) {
  const rawInput = String(body?.url || "");
  const normalizedUrl = normalizeYouTubeUrl(rawInput);
  const id = videoId(rawInput);
  if (!id) {
    res.statusCode = 400;
    res.end(JSON.stringify({ error: "不是有效的 YouTube 链接或 videoId", reason: "invalid_video_id", diagnostics: { rawInput, normalizedUrl } }));
    return;
  }

  const cached = transcriptCache.get(id);
  if (cached && Date.now() - cached.savedAt < TRANSCRIPT_CACHE_TTL_MS) {
    res.statusCode = 200;
    res.end(JSON.stringify(successPayload(cached.value.result, rawInput, normalizedUrl, { cached: true, serviceFallback: cached.value.serviceFallback })));
    return;
  }
  transcriptCache.delete(id);

  let request = transcriptRequests.get(id);
  if (!request) {
    request = resolveTranscript(rawInput, env)
      .then((value) => { cacheTranscript(id, value); return value; })
      .finally(() => transcriptRequests.delete(id));
    transcriptRequests.set(id, request);
  }

  try {
    const { result, serviceFallback } = await request;
    res.statusCode = 200;
    res.end(JSON.stringify(successPayload(result, rawInput, normalizedUrl, { serviceFallback })));
  } catch (error) {
    const knownError = error instanceof TranscriptExtractionError;
    const statusCode = knownError ? error.statusCode : 502;
    const diagnostics = knownError ? error.diagnostics : [];
    const isBotChallenge = knownError && error.reason === "youtube_bot_challenge";
    res.statusCode = statusCode;
    res.end(JSON.stringify({
      error: isBotChallenge
      ? "YouTube 的服务器端 bot challenge 阻止读取该视频已有的 CC Transcript；浏览器历史路径也可能受限。"
        : error?.message || "未能读取 YouTube 已有英文 CC Transcript",
      reason: knownError ? error.reason : "transcript_unavailable",
      errors: knownError ? error.errors : [],
      diagnostics: {
        rawInput,
        normalizedUrl,
        videoId: videoId(rawInput),
        apiUrl: "/api/youtube-transcript",
        captionTracksFound: Math.max(0, ...diagnostics
          .filter((item) => item.step === "caption-tracks")
          .map((item) => item.found || 0)),
        subtitleCount: 0,
        transcriptService: error?.serviceFallback || null,
        serverAttempts: 3,
        upstream: diagnostics,
      },
    }));
  }
}
